// Generated by Claude Sonnet 5. Not hand-written by the project author.

import { promises as fs } from 'node:fs';
import path from 'node:path';

// Subdirectories in the official test/ tree that target earlier book
// chapters or the tree-walk-only parts of the suite, rather than a
// clox-style bytecode VM. Adjust this list to match what your VM actually
// implements -- e.g. remove entries here as you implement more of the
// language, or add more if your port stops earlier than full clox.
const DEFAULT_EXCLUDED_DIRS = new Set<string>([
  'benchmark', // performance scripts -- not pass/fail tests, run these separately
  'scanning', // targets the standalone scanner from early chapters
  'expressions', // targets the standalone expression evaluator from early chapters
]);

export interface DiscoverOptions {
  excludedDirs?: Set<string>;
}

export async function discoverTestFiles(
  rootDir: string,
  options: DiscoverOptions = {}
): Promise<string[]> {
  const excluded = options.excludedDirs ?? DEFAULT_EXCLUDED_DIRS;
  const results: string[] = [];

  async function walk(dir: string): Promise<void> {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (excluded.has(entry.name)) continue;
        await walk(fullPath);
      } else if (entry.isFile() && entry.name.endsWith('.lox')) {
        results.push(fullPath);
      }
    }
  }

  await walk(rootDir);
  results.sort();
  return results;
}
