// Generated by Claude Sonnet 5. Not hand-written by the project author.

import path from 'node:path';
import { promises as fs } from 'node:fs';
import { discoverTestFiles } from './discover';
import { parseExpectations } from './parser';
import { runTest } from './runner';
import { printReport } from './report';
import { TestOutcome } from './types';

// rox/mothership/test, resolved relative to this file (works the same from
// src/ under tsx and from dist/ after `npm run build`, since both sit one
// directory below rox/wasm_harness_server).
const TEST_ROOT = path.resolve(__dirname, '../../mothership/test');

async function main(): Promise<void> {
  const testFiles = await discoverTestFiles(TEST_ROOT);
  console.log(`Discovered ${testFiles.length} test files under ${TEST_ROOT}`);
  console.log('');

  const outcomes: TestOutcome[] = [];
  for (const filePath of testFiles) {
    const source = await fs.readFile(filePath, 'utf8');
    const expectation = parseExpectations(filePath, source);
    const outcome = await runTest(expectation, source);
    outcomes.push(outcome);
  }

  printReport(outcomes);

  const anyFailed = outcomes.some((o) => o.status === 'fail');
  process.exitCode = anyFailed ? 1 : 0;
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
