// Generated by Claude Sonnet 5. Not hand-written by the project author.
//
// Reimplements, in TypeScript, the test-expectation comment conventions used
// by the official craftinginterpreters Lox test suite and its Dart test
// runner (tool/bin/test.dart -- see
// https://github.com/munificent/craftinginterpreters/blob/master/README.md
// for the general description of how the suite works). This is a
// best-effort port of the documented convention, not a verified line-for-line
// copy of the Dart source. If a specific test file parses unexpectedly,
// compare its comments against tool/bin/test.dart in that repository.

import { CompileErrorExpectation, TestExpectation } from './types';

// "// expect: <output>" -- one expected line of stdout, in file order.
const EXPECTED_OUTPUT_PATTERN = /\/\/\s*expect:\s?(.*)/;

// "// expect runtime error: <message>"
const EXPECTED_RUNTIME_ERROR_PATTERN = /\/\/\s*expect runtime error:\s*(.+)/;

// "// [line 3] Error at 'x': message"
// "// [c line 3] Error ...."     (only expected for the C/bytecode-style implementation)
// "// [java line 3] Error ...."  (only expected for the tree-walk implementation)
const ERROR_LINE_PATTERN = /\/\/\s*\[(?:(java|c)\s+)?line (\d+)\]\s*(Error.+)/;

// "// Error at 'x': message" with no explicit [line N] -- the error is expected
// on the physical line the comment appears on.
const BARE_ERROR_PATTERN = /\/\/\s*(Error.+)/;

// "// nontest" -- marks a file that exists to be included by other tests
// and isn't meant to be run as a test on its own.
const NONTEST_PATTERN = /\/\/\s*nontest/;

// This harness targets a clox-style bytecode VM. Change to 'java' if you're
// testing a tree-walk implementation instead.
const LANGUAGE: 'c' | 'java' = 'c';

export function parseExpectations(testPath: string, source: string): TestExpectation {
  const lines = source.split(/\r\n|\n/);

  const expectedOutput: string[] = [];
  const expectedCompileErrors: CompileErrorExpectation[] = [];
  let expectedRuntimeError: TestExpectation['expectedRuntimeError'] = null;
  let skip = false;

  lines.forEach((line, index) => {
    const lineNumber = index + 1;

    if (NONTEST_PATTERN.test(line)) {
      skip = true;
      return;
    }

    const runtimeMatch = line.match(EXPECTED_RUNTIME_ERROR_PATTERN);
    if (runtimeMatch) {
      expectedRuntimeError = { message: runtimeMatch[1], line: lineNumber };
      return;
    }

    const errorLineMatch = line.match(ERROR_LINE_PATTERN);
    if (errorLineMatch) {
      const [, language, lineStr, message] = errorLineMatch;
      // A "[java line N]" comment is only a requirement for the tree-walk
      // implementation, and vice versa -- skip it if it doesn't apply here.
      if (language && language !== LANGUAGE) return;
      expectedCompileErrors.push({ line: Number(lineStr), message });
      return;
    }

    const bareErrorMatch = line.match(BARE_ERROR_PATTERN);
    if (bareErrorMatch) {
      expectedCompileErrors.push({ line: lineNumber, message: bareErrorMatch[1] });
      return;
    }

    const outputMatch = line.match(EXPECTED_OUTPUT_PATTERN);
    if (outputMatch) {
      expectedOutput.push(outputMatch[1]);
    }
  });

  // A file with an expected compile error never gets far enough to hit a
  // runtime error, regardless of what other comments say.
  if (expectedCompileErrors.length > 0) {
    expectedRuntimeError = null;
  }

  return {
    path: testPath,
    expectedOutput,
    expectedRuntimeError,
    expectedCompileErrors,
    skip,
  };
}
