// Generated by Claude Sonnet 5. Not hand-written by the project author.

import { TestOutcome } from './types';

const GREEN = '\x1b[32m';
const RED = '\x1b[31m';
const YELLOW = '\x1b[33m';
const RESET = '\x1b[0m';

export function printReport(outcomes: TestOutcome[]): void {
  let passed = 0;
  let failed = 0;
  let skipped = 0;
  const failures: Extract<TestOutcome, { status: 'fail' }>[] = [];

  for (const outcome of outcomes) {
    switch (outcome.status) {
      case 'pass':
        passed += 1;
        console.log(`${GREEN}PASS${RESET}  ${outcome.path}`);
        break;
      case 'skip':
        skipped += 1;
        console.log(`${YELLOW}SKIP${RESET}  ${outcome.path}  (${outcome.reason})`);
        break;
      case 'fail':
        failed += 1;
        failures.push(outcome);
        console.log(`${RED}FAIL${RESET}  ${outcome.path}  (${outcome.reason})`);
        break;
    }
  }

  console.log('');
  console.log(`Passed: ${passed}  Failed: ${failed}  Skipped: ${skipped}  Total: ${outcomes.length}`);

  if (failures.length > 0) {
    console.log('');
    console.log('--- Failure detail ---');
    for (const failure of failures) {
      console.log('');
      console.log(`${failure.path}: ${failure.reason}`);
      console.log('  expected:', JSON.stringify(failure.expected));
      console.log('  actual:  ', JSON.stringify(failure.actual));
    }
  }
}
