// Generated by Claude Sonnet 5. Not hand-written by the project author.
//
// Loads the wasm-bindgen module built from rox/library and drives it
// against a single parsed test expectation.
//
// Prerequisite: build the library for Node with:
//   cd rox/library && wasm-pack build --target nodejs --out-dir pkg
//
// `--target nodejs` produces a synchronous CommonJS module (no async init()
// call required), which is what lets this file `require`/`import` it
// directly. That's a different build target from whatever you use for the
// browser harness (`--target web`) -- the two can share the same `src/lib.rs`
// but need separate `wasm-pack build` invocations, typically into separate
// output directories, since the generated JS glue differs.

import { LoxRunner } from '../../library/pkg/rox_lib';
import { CompileErrorExpectation, TestExpectation, TestOutcome } from './types';

export async function runTest(expectation: TestExpectation, source: string): Promise<TestOutcome> {
  if (expectation.skip) {
    return { status: 'skip', path: expectation.path, reason: 'marked // nontest' };
  }

  const runner = new LoxRunner();
  let actualOutput: string[] | null = null;
  let thrown: string | null = null;

  try {
    actualOutput = runner.run(source);
  } catch (err) {
    // A Rust `Result<String, String>` exported via wasm-bindgen converts
    // Err(value) into a *thrown* JS value equal to that String -- it does
    // not come back as a normal return value. See
    // https://github.com/wasm-bindgen/wasm-bindgen/blob/main/guide/src/reference/types/result.md
    thrown = (err as string[]).join("");
  }

  return compare(expectation, actualOutput, thrown);
}

function splitLines(text: string): string[] {
  // Drop one trailing newline so a program whose last statement is `print`
  // doesn't produce a spurious empty final "line" when compared.
  const trimmed = text.replace(/\n$/, '');
  return trimmed.length === 0 ? [] : trimmed.split('\n');
}

function compare(expectation: TestExpectation, actualOutput: string[] | null, thrown: string | null): TestOutcome {
  const { path: testPath, expectedOutput, expectedRuntimeError, expectedCompileErrors } = expectation;
  const expectedFailure = expectedCompileErrors.length > 0 || expectedRuntimeError !== null;

  if (expectedFailure) {
    if (thrown === null) {
      return {
        status: 'fail',
        path: testPath,
        reason: 'expected a failure but the program ran to completion',
        expected: expectedCompileErrors.length > 0 ? expectedCompileErrors : expectedRuntimeError,
        actual: actualOutput,
      };
    }

    if (expectedRuntimeError) {
      if (!thrown.includes(expectedRuntimeError.message)) {
        return {
          status: 'fail',
          path: testPath,
          reason: 'runtime error message did not match',
          expected: expectedRuntimeError,
          actual: thrown,
        };
      }
      return { status: 'pass', path: testPath };
    }

    // Compile errors: check that every expected message appears somewhere in
    // the combined error output. This is a loose substring match rather than
    // requiring exact line-for-line agreement, since exact wording is one of
    // the more implementation-specific details of a from-scratch Lox port.
    const missing = expectedCompileErrors.filter((e) => !thrown!.includes(render(e)));
    if (missing.length > 0) {
      return {
        status: 'fail',
        path: testPath,
        reason: 'one or more expected compile errors were not found in the output',
        expected: expectedCompileErrors,
        actual: thrown,
      };
    }
    return { status: 'pass', path: testPath };
  }

  // No failure was expected.
  if (thrown !== null) {
    return {
      status: 'fail',
      path: testPath,
      reason: 'program failed but no error was expected',
      expected: expectedOutput,
      actual: thrown,
    };
  }

  const actualLines = (actualOutput ?? []).flatMap(splitLines);
  const outputMatches =
    actualLines.length === expectedOutput.length && actualLines.every((line, i) => line === expectedOutput[i]);

  if (!outputMatches) {
    return {
      status: 'fail',
      path: testPath,
      reason: 'output did not match',
      expected: expectedOutput,
      actual: actualLines,
    };
  }

  return { status: 'pass', path: testPath };
}

function render(expectation: CompileErrorExpectation) {
  return `[line ${expectation.line}] ${expectation.message}`;
}
