// Generated by Claude Sonnet 5. Not hand-written by the project author.

export interface CompileErrorExpectation {
  line: number;
  message: string;
}

export interface RuntimeErrorExpectation {
  message: string;
  line: number;
}

export interface TestExpectation {
  path: string;
  expectedOutput: string[];
  expectedRuntimeError: RuntimeErrorExpectation | null;
  expectedCompileErrors: CompileErrorExpectation[];
  /** Set when the file is marked `// nontest` and should not be executed at all. */
  skip: boolean;
}

export type TestOutcome =
  | { status: 'pass'; path: string }
  | { status: 'skip'; path: string; reason: string }
  | {
      status: 'fail';
      path: string;
      reason: string;
      expected: unknown;
      actual: unknown;
    };
